// Code generated by "stringer -type=KeyState"; DO NOT EDIT.

package ps4

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyUp-0]
	_ = x[KeyDown-1]
}

const _KeyState_name = "KeyUpKeyDown"

var _KeyState_index = [...]uint8{0, 5, 12}

func (i KeyState) String() string {
	if i >= KeyState(len(_KeyState_index)-1) {
		return "KeyState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyState_name[_KeyState_index[i]:_KeyState_index[i+1]]
}
